CREATE TABLE IF NOT EXISTS shift_swap_documents (
  id INT(11) NOT NULL AUTO_INCREMENT,
  swap_request_id INT(11) NOT NULL,
  document_status VARCHAR(40) NOT NULL DEFAULT 'requester_signed',
  requester_signature_path VARCHAR(255) DEFAULT NULL,
  responder_signature_path VARCHAR(255) DEFAULT NULL,
  approver_signature_path VARCHAR(255) DEFAULT NULL,
  requester_signed_at DATETIME DEFAULT NULL,
  responder_signed_at DATETIME DEFAULT NULL,
  approver_signed_at DATETIME DEFAULT NULL,
  requester_name_snapshot VARCHAR(255) DEFAULT NULL,
  responder_name_snapshot VARCHAR(255) DEFAULT NULL,
  approver_name_snapshot VARCHAR(255) DEFAULT NULL,
  requester_position_snapshot VARCHAR(255) DEFAULT NULL,
  responder_position_snapshot VARCHAR(255) DEFAULT NULL,
  approver_position_snapshot VARCHAR(255) DEFAULT NULL,
  requester_department_snapshot VARCHAR(255) DEFAULT NULL,
  responder_department_snapshot VARCHAR(255) DEFAULT NULL,
  approver_department_snapshot VARCHAR(255) DEFAULT NULL,
  requester_shift_snapshot TEXT DEFAULT NULL,
  responder_shift_snapshot TEXT DEFAULT NULL,
  reason_snapshot TEXT DEFAULT NULL,
  target_response_note_snapshot TEXT DEFAULT NULL,
  manager_response_note_snapshot TEXT DEFAULT NULL,
  pdf_path VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shift_swap_documents_request (swap_request_id),
  KEY idx_shift_swap_documents_status (document_status),
  CONSTRAINT fk_shift_swap_documents_request
    FOREIGN KEY (swap_request_id) REFERENCES shift_swap_requests(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
