CREATE TABLE IF NOT EXISTS shift_swap_requests (
  id INT(11) NOT NULL AUTO_INCREMENT,
  requester_id INT(11) NOT NULL,
  target_staff_id INT(11) NOT NULL,
  requester_assignment_id INT(11) NOT NULL,
  target_assignment_id INT(11) NOT NULL,
  department_id INT(11) NOT NULL,
  swap_type VARCHAR(30) NOT NULL DEFAULT 'swap_with_person',
  reason TEXT NULL,
  target_response_note TEXT NULL,
  manager_response_note TEXT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending_target_confirm',
  target_confirmed_at DATETIME NULL,
  target_rejected_at DATETIME NULL,
  manager_approved_by INT(11) NULL,
  manager_approved_at DATETIME NULL,
  manager_rejected_by INT(11) NULL,
  manager_rejected_at DATETIME NULL,
  applied_at DATETIME NULL,
  cancelled_by INT(11) NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_swap_requester (requester_id),
  KEY idx_swap_target (target_staff_id),
  KEY idx_swap_department_status (department_id, status),
  KEY idx_swap_requester_assignment (requester_assignment_id),
  KEY idx_swap_target_assignment (target_assignment_id),
  KEY idx_swap_status (status),
  CONSTRAINT fk_shift_swap_requester FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT fk_shift_swap_target FOREIGN KEY (target_staff_id) REFERENCES users(id),
  CONSTRAINT fk_shift_swap_requester_assignment FOREIGN KEY (requester_assignment_id) REFERENCES shift_assignments(id),
  CONSTRAINT fk_shift_swap_target_assignment FOREIGN KEY (target_assignment_id) REFERENCES shift_assignments(id),
  CONSTRAINT fk_shift_swap_department FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_shift_swap_manager_approved_by FOREIGN KEY (manager_approved_by) REFERENCES users(id),
  CONSTRAINT fk_shift_swap_manager_rejected_by FOREIGN KEY (manager_rejected_by) REFERENCES users(id),
  CONSTRAINT fk_shift_swap_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
