CREATE TABLE IF NOT EXISTS shift_cover_requests (
  id INT(11) NOT NULL AUTO_INCREMENT,
  requester_id INT(11) NOT NULL,
  substitute_staff_id INT(11) NOT NULL,
  source_assignment_id INT(11) NOT NULL,
  department_id INT(11) NOT NULL,
  reason TEXT NULL,
  substitute_response_note TEXT NULL,
  manager_response_note TEXT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending_substitute_confirm',
  substitute_confirmed_at DATETIME NULL,
  substitute_rejected_at DATETIME NULL,
  manager_approved_by INT(11) NULL,
  manager_approved_at DATETIME NULL,
  manager_rejected_by INT(11) NULL,
  manager_rejected_at DATETIME NULL,
  applied_at DATETIME NULL,
  cancelled_by INT(11) NULL,
  cancelled_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_cover_requester (requester_id),
  KEY idx_cover_substitute (substitute_staff_id),
  KEY idx_cover_source_assignment (source_assignment_id),
  KEY idx_cover_department_status (department_id, status),
  KEY idx_cover_status (status),
  CONSTRAINT fk_shift_cover_requester FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT fk_shift_cover_substitute FOREIGN KEY (substitute_staff_id) REFERENCES users(id),
  CONSTRAINT fk_shift_cover_source_assignment FOREIGN KEY (source_assignment_id) REFERENCES shift_assignments(id),
  CONSTRAINT fk_shift_cover_department FOREIGN KEY (department_id) REFERENCES departments(id),
  CONSTRAINT fk_shift_cover_manager_approved_by FOREIGN KEY (manager_approved_by) REFERENCES users(id),
  CONSTRAINT fk_shift_cover_manager_rejected_by FOREIGN KEY (manager_rejected_by) REFERENCES users(id),
  CONSTRAINT fk_shift_cover_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS shift_cover_documents (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cover_request_id INT(11) NOT NULL,
  document_status VARCHAR(40) NOT NULL DEFAULT 'requester_signed',
  requester_signature_path VARCHAR(255) DEFAULT NULL,
  substitute_signature_path VARCHAR(255) DEFAULT NULL,
  approver_signature_path VARCHAR(255) DEFAULT NULL,
  requester_signed_at DATETIME DEFAULT NULL,
  substitute_signed_at DATETIME DEFAULT NULL,
  approver_signed_at DATETIME DEFAULT NULL,
  requester_name_snapshot VARCHAR(255) DEFAULT NULL,
  substitute_name_snapshot VARCHAR(255) DEFAULT NULL,
  approver_name_snapshot VARCHAR(255) DEFAULT NULL,
  requester_position_snapshot VARCHAR(255) DEFAULT NULL,
  substitute_position_snapshot VARCHAR(255) DEFAULT NULL,
  approver_position_snapshot VARCHAR(255) DEFAULT NULL,
  requester_department_snapshot VARCHAR(255) DEFAULT NULL,
  substitute_department_snapshot VARCHAR(255) DEFAULT NULL,
  approver_department_snapshot VARCHAR(255) DEFAULT NULL,
  source_shift_snapshot TEXT DEFAULT NULL,
  reason_snapshot TEXT DEFAULT NULL,
  substitute_response_note_snapshot TEXT DEFAULT NULL,
  manager_response_note_snapshot TEXT DEFAULT NULL,
  pdf_path VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_shift_cover_documents_request (cover_request_id),
  KEY idx_shift_cover_documents_status (document_status),
  CONSTRAINT fk_shift_cover_documents_request
    FOREIGN KEY (cover_request_id) REFERENCES shift_cover_requests(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
